
 
import time
 
from selenium import webdriver
from selenium.common.exceptions import UnexpectedAlertPresentException
from selenium.webdriver.common.keys import Keys
 
# driver = webdriver.Firefox(executable_path='<Path>/geckodriver.exe')
# This block of code is used to block the notification popup which is generated by site
options = webdriver.ChromeOptions()
options.add_argument("--disable-notifications")
 
# to open chrome webbrowser and maximize the window
driver = webdriver.Chrome(executable_path="chromedriver.exe", chrome_options=options)
driver.maximize_window()
 
#Implicit Wait when element is taking time to load
driver.implicitly_wait(20)
 
# connect to the specific ip address
driver.get("https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Computer+Science+professors&btnG=")
list_of_links = [] 

for i in range (2):
    next = driver.find_element_by_xpath("//div/button[2]")
    profilePicList = driver.find_elements_by_xpath("//div/h3/a")
    for p in profilePicList:
        pURL = p.get_attribute("href")
        list_of_links.append(pURL)
    next.send_keys(Keys.END)

    next.click()
    time.sleep(10)
print(len(list_of_links))
for each in list_of_links:
    driver.get(each)
    name = driver.find_element_by_id("gsc_prf_in").text
    print(name)
    h_index = driver.find_element_by_xpath("//*[@id='gsc_rsb_st']/tbody/tr[2]/td[2]").text
    print("Overall h index "+str(h_index))
  
    
